config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :students
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :colleges, except: [:destroy]
  resources :courses, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college.rb
class College < ApplicationRecord
  has_many :student_colleges
  has_many :students, through: :student_colleges
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :student_courses
  has_many :students, through: :student_courses
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
    has_many :student_colleges
    has_many :colleges, through: :student_colleges
    has_many :student_courses
    has_many :courses, through: :student_courses
  validates :student_name, presence: true, length: { minimum: 3, maximum: 15 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email_id, presence: true, uniqueness: true, length: { maximum: 35}, format: { with: VALID_EMAIL_REGEX }
  validates :address, presence: true, length: { minimum: 10, maximum: 50 }
  validates :contact_number, presence: true, length: { minimum: 10, maximum: 10 }
  validates :marks, presence: true, :inclusion => 100..500
end

app/models/student_college.rb
class StudentCollege < ApplicationRecord
  belongs_to :student
  belongs_to :college
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :students
  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, length: { maximum: 35}, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in? 
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
before_action :set_college, only: [:show, :edit, :update]
  
  def show
  end
    
  def index
    @colleges = College.all
  end

  def new
    @college = College.new
  end

  def create
    @college = College.new(college_params)
    if @college.save
      flash[:notice] = "College Name was successfully created"
      redirect_to @college
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @college.update(college_params)
      flash[:notice] = "College Name was successfully updated"
      redirect_to @college
    else
      render 'edit'
    end
  end

  private

  def set_college
    @college = College.find(params[:id])
  end

  def college_params
    params.require(:college).permit(:name)
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update]

  def show
  end

  def index
    @courses = Course.all
  end

  def new
      @course = Course.new
  end

  def edit
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:notice] = "Course Name was successfully created"
      redirect_to @course
    else
      render 'new'
    end
  end

  def update
    if @course.update(course_params)
      flash[:notice] = "Course Name was successfully updated"
      redirect_to @course
    else
      render 'edit'
    end
  end

  private

  def course_params
    params.require(:course).permit(:name)
  end

  def set_course
    @course = Course.find(params[:id])
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to user_path(current_user) if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
    
  def create
    user = User.find_by(email: params[:session][:email.downcase])
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:notice] = "Logged in successfully"
        redirect_to user
    else
      flash.now[:alert] = "Oops! Something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
  
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def show
  end

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def create
    @student = Student.new(student_params)
    @student.user = current_user
    if @student.save
      flash[:notice] = "Your Details was saved successfully"
      redirect_to student_path(@student)
    else
      render 'new'
    end
  end

  def update
    if @student.update(student_params)
      flash[:notice] = "Your Details was updated successfully"
      redirect_to @student
    else
      render 'edit'
    end
  end
  
  def destroy
    @student.destroy
    redirect_to students_path
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:student_name, :email_id, 
                                   :address, :contact_number, :marks, college_ids: [], course_ids: [])
  end

  def require_same_user
    if current_user != @student.user && !current_user.admin?
      flash[:alert] = "Sorry! You can edit only your details"
      redirect_to current_user
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def show
    @students = @user.students
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Student Portal #{@user.username}, you have successfully signedup"
      redirect_to new_student_path(@student)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice]="Your account information was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:alert] = "Sorry! You can edit only your profile"
      redirect_to current_user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/colleges/_college.html.erb
<ul>
  <li> <%= college.name %> </li>
</ul>

app/views/colleges/_form.html.erb
</br>
<% if @college.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">Oops! The Following errors prevented from being saved</h4>
    <ul>
      <% @college.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
	  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	    <span aria-hidden="true">&times;</span>
	  </button>
  </div>  	
<% end %>

<%= form_with(model: @college, local: true) do |j| %>

	<div class="form-group row">
	  <%= j.label :name, "College name", class: "col-2 col-form-label" %>
	    <div class="col-5">
	      <%= j.text_field :name, class: "form-control" %>
	    </div>
	</div>
	  
	<div class="form-group row, text-center">
	  <%= j.submit class: "btn btn-secondary" %>
	</div></br>
  
<% end %>

app/views/colleges/edit.html.erb
<h1 class="text-center mt-4">Edit College</h1>

<% if current_user.admin? %>
  <div class="container" id="new-container">
  </br>
  <%= render 'form' %>
  
<% else %></br>
  <h2><center>Oops! Only Admin has the right to edit the College name</center></h2>
  </div> 
<% end %> 

app/views/colleges/index.html.erb
<h1 class="text-center mt-4">College List</h1>

<% if current_user.admin? %>
  <div class="container" id="index-container">
    </br>
    <% @colleges.each do |college| %>
      <div class="card mt-4" style="width: 35rem;">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">College Name: <%= college.name %> </li>
        </ul>
      </div>
      
      <div class="mt-2">
        <%= link_to "EDIT COLLEGE NAME", edit_college_path(college), class: "btn btn-secondary" %></br></br>
      </div>
    <% end %>

<% else %></br>
  <h2><center>Oops! Only Admin has the right to view College list</center></h2>
<% end %>
</div>

app/views/colleges/new.html.erb
<h1 class="text-center mt-4">Create New College</h1>

<% if current_user.admin? %>
  <div class="container" id="new-container">
  </br>
    <%= render 'form' %>
    
<% else %></br>
 <h2><center>Oops! Only Admin has the right to edit the College name</center></h2>
  </div>
<% end %>

app/views/colleges/show.html.erb
<h1 class="text-center mt-4">College Name: <%= @college.name %></h1>

app/views/courses/_course.html.erb
<ul>
  <li> <%= course.name %> </li>
</ul>

app/views/courses/_form.html.erb
</br>
<% if @course.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">Oops! The Following errors prevented from being saved</h4>
    <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
	  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	    <span aria-hidden="true">&times;</span>
	  </button>
  </div>  	
<% end %>

<%= form_with(model: @course, local: true) do |j| %>
	<div class="form-group row">
	  <%= j.label :name, "Course name", class: "col-2 col-form-label" %>
	    <div class="col-5">
	     <%= j.text_field :name, class: "form-control" %>
	   </div>
	</div>

	<div class="form-group row, text-center">
	  <%= j.submit class: "btn btn-secondary" %>
	</div></br>
  
<% end %>

app/views/courses/edit.html.erb
<h1 class="text-center mt-4">Edit Course</h1>
<% if current_user.admin? %>
  <div class="container" id="new-container">
    </br>
    <%= render 'form' %>

<% else %></br>
  <h2><center>Oops! Only Admin has the right to edit the Course name</center></h2>
  </div>
<% end %>

app/views/courses/index.html.erb
<h1 class="text-center mt-4">Course List</h1>

<% if current_user.admin? %>
  <div class="container" id="index-container">
    </br>
    <% @courses.each do |course| %>
      <div class="card mt-4" style="width: 22rem;">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Course Name: <%= course.name %> </li>
        </ul>
      </div>

      <div class="mt-2">
        <%= link_to "EDIT COURSE NAME", edit_course_path(course), class: "btn btn-secondary" %></br></br>
      </div>
    <% end %>

<% else %></br>
  <h2><center>Oops! Only Admin has the right to view Course list</center></h2>
<% end %>
  
</div>

app/views/courses/new.html.erb
<h1 class="text-center mt-4">Create New Course</h1>
<% if current_user.admin? %>
  <div class="container" id="new-container">
    </br>
    <%= render 'form' %>
    
<% else %></br>
  <h2><center>Oops! Only Admin has the right to edit the Course name</center></h2>
<% end %>

</div>

app/views/courses/show.html.erb
<h1 class="text-center mt-4">Course Name: <%= @course.name %></h1>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
  <% end %> 
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <% if logged_in? %>
    <%= link_to "My Form", root_path, class: "navbar-brand", id: "logo" %>
  <% else %>
    <%= link_to "STUDENT PORTAL", root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if logged_in? %>
      <li class="nav-item active">
        <%= link_to "STUDENTS DETAIL", students_path, class: "nav-link" %>
      </li>
    <% end %>

    <% if logged_in? && current_user.admin? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= "COLLEGE" %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Create New College", new_college_path, class: "dropdown-item" %>
          <%= link_to "View College List", colleges_path, class: "dropdown-item" %>
        </div>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      </li>
    <% end %>

    <% if logged_in? && current_user.admin? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= "COURSE" %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Create New Course", new_course_path, class: "dropdown-item" %>
          <%= link_to "View Course List", courses_path, class: "dropdown-item" %>
        </div>
      </li>
    <% end %>

    <% if logged_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= "(Admin)" if current_user.admin? %> <%= current_user.username.upcase %>
        </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Application Form", new_student_path, class: "dropdown-item" %>
            <%= link_to "Edit your Profile", edit_user_path(current_user), class: "dropdown-item" %>
          </div>
      </li>

      <li class="nav-item">
        <%= link_to "LOGOUT", logout_path, class: "nav-link", method: :delete %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "LOGIN", login_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "SIGNUP", signup_path, class: "btn btn-danger btn" %>
      </li>
    <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentPortal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h2 class="text-center mt-4">WELCOME TO STUDENT PORTAL !!!</h2>

  <div class="container text-center text-green" id="home-container">
  </div>

app/views/students/_form.html.erb
<div class="container">
  </br>
  <% if @student.errors.any? %>
	  <div class="alert alert-danger alert-dismissible fade show" role="alert">
	  <h4 class="alert-heading">Oops! The Following errors prevented from being saved</h4>
	    <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      
		  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		    <span aria-hidden="true">&times;</span>
		  </button>
	  </div>  	
  <% end %>

  </br>
  <%= form_with(model: @student, local: true) do |j| %>

    <div class="form-group row">
      <%= j.label :student_name, "Student Name", class: "col-2 col-form-label" %>
        <div class="col-5">
        	<%= j.text_field :student_name, class: "form-control" %>
    	  </div>
	  </div>
	  
    <div class="form-group row"> 
      <%= j.label :email_id,"Email Id", class: "col-2 col-form-label" %>
        <div class="col-5">
          <%= j.text_field :email_id, class: "form-control" %>
        </div>
    </div>

    <div class="form-group row">
      <%= j.label :address, "Contact Address", class: "col-2 col-form-label" %>
        <div class="col-5">
          <%= j.text_field :address, row: 5, class: "form-control" %>
        </div>
    </div>

    <div class="form-group row">
      <%= j.label :contact_number, "Contact Number", class: "col-2 col-form-label" %>
        <div class="col-5">
          <%= j.text_field :contact_number, class: "form-control" %>
        </div>
    </div>

  	<div class="form-group row">
	    <%= j.label :marks, "Marks Scored", class: "col-2 col-form-label" %>
	      <div class="col-5">
	        <%= j.text_field :marks, class: "form-control" %>
	      </div>
	  </div>

	  <div class="form-group row">
	    <%= j.label :college, "Choose College", class: "col-2 col-form-label" %>
	      <div class="col-5">
	        <%= j.collection_select(:college_ids, College.all, :id, :name,
		                       {prompt: "Available Colleges"}, { multiple: true, class: "custom-select"} ) %>
	      </div>
	  </div>

	  <div class="form-group row">
      <%= j.label :course, "Choose Course", class: "col-2 col-form-label" %>
        <div class="col-5">
          <%= j.collection_select(:course_ids, Course.all, :id, :name,
                             {prompt: "Available Courses"}, { multiple: true, class: "custom-select"} ) %>
        </div>
    </div></br>
	  
	  <div class="form-group row, text-center">
	    <%= j.submit "Submit your Application Form", class: "btn btn-secondary" %>
	  </div></br>
<% end %>
</div>

app/views/students/_student.html.erb
<div class="container" id="index-container">
</br>
  <% @students.each do |student| %>
    <div class="card mt-4" style="width: 32rem;">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Student Name: <%= student.student_name.capitalize %> </li>
        <li class="list-group-item">Email Id: <%= student.email_id %> </li>
        <li class="list-group-item">Contact Address: <%= student.address %> </li>
        <li class="list-group-item">Contact Number: <%= student.contact_number %> </li>
        <li class="list-group-item">Marks Scored: <%= student.marks %> </li>

        <li class="list-group-item">Preferred College: <%= render student.colleges %> </li>
        <li class="list-group-item">Preferred Course: <%= render student.courses %>  </li>

        <% if logged_in? && (student.user == current_user || current_user.admin?) %>
          <li class="list-group-item"><%= link_to "EDIT", edit_student_path(student), class: "btn btn-secondary"%> </li>
          <li class="list-group-item"><%= link_to "DELETE", student_path(student), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %></li>
        <% end %>
      </ul>
      
    </div></br>
  <% end %>
</div>

app/views/students/edit.html.erb
<h2 class="text-center mt-4">EDIT YOUR APPLICATION FORM</h2></br>

<div class="container" id="new-container">
  <%= render 'form' %>
  <div class="form-group row, text-center">
    <%= link_to "Cancel and Back to the profile", student_path(@student), class: "btn btn-secondary" %> </br>
  </div></br>
</div></br>

app/views/students/index.html.erb
<h2 class="text-center mt-4">STUDENT DETAILS</h2>
<% if current_user.admin? %>
  </br>
  <%= render 'student' %>
  
<% else %></br>
  <h2><center>Oops! Only Admin can view student details</center></h2>
<% end %>

app/views/students/new.html.erb
<h2 class="text-center mt-4">Fill the Application Form</h2></br>

<div class="container" id="new-container">
  <%= render 'form' %>
</div>

app/views/students/show.html.erb
<h2 class="text-center mt-4"><%= @student.student_name.upcase %> Application Form</h2>

</br>
<div class="container" id="show-container"></br>

  <div class="card mt-4" style="width: 32rem;">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Student Name: <%= @student.student_name.capitalize %> </li>
      <li class="list-group-item">Email Id: <%= @student.email_id %> </li>
      <li class="list-group-item">Contact Address: <%= @student.address %> </li>
      <li class="list-group-item">Contact Number: <%= @student.contact_number %> </li>
      <li class="list-group-item">Marks Scored: <%= @student.marks %> </li>

      <li class="list-group-item">Preferred College: <%= render @student.colleges %>  </li>
      <li class="list-group-item">Preferred Course: <%= render @student.courses %>  </li>
    </ul>
  </div>
  
  <div class="text-center mt-4">
    <% if @student.new_record? %>
      <%= link_to "CREATE YOUR FORM", new_student_path(@student), class: "btn btn-secondary" %></br></br>
    <% else %>
      <%= link_to "EDIT YOUR FORM", edit_student_path(@student), class: "btn btn-secondary" %></br></br>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<div class="container">
	</br>
	<% if @user.errors.any? %>
		<div class="alert alert-danger alert-dismissible fade show" role="alert">
	  <h4 class="alert-heading">Oops! The Following errors prevented from being saved</h4>
	    <ul>
		    <% @user.errors.full_messages.each do |msg| %>
			    <li><%= msg %></li>
		    <% end %>
      </ul>
      
		  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
			  <span aria-hidden="true">&times;</span>
		  </button>
	  </div>  	
	<% end %>

  </br>
  <%= form_with(model: @user, local: true) do |j| %>

    <div class="form-group row">
      <%= j.label :username, class: "col-2 col-form-label" %>
        <div class="col-5">
          <%= j.text_field :username, class: "form-control" %>
        </div>
    </div>
      
    <div class="form-group row">
      <%= j.label :email, class: "col-2 col-form-label" %>
        <div class="col-5">
          <%= j.email_field :email, class: "form-control" %>
        </div>
    </div>

    <div class="form-group row">
      <%= j.label :password, class: "col-2 col-form-label" %>
        <div class="col-5">
          <%= j.text_field :password, class: "form-control" %>
        </div>
    </div>
      
    <div class="form-group row, text-center">
      <%= j.submit(@user.new_record? ? "SIGN UP" : "Update account", class: "btn btn-secondary") %>
    </div></br>
  
  <% end %>
</div>

app/views/users/edit.html.erb
<h2 class="text-center mt-4">Edit your Profile</h2></br>

<div class="container" id="new-container">
  <%= render 'form' %>
</div>

app/views/users/new.html.erb
<h2 class="text-center mt-4">Create your Profile</h2></br>

<div class="container" id="new-container">
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<h2 class="text-center mt-4"><%= @user.username.upcase %> Application Form</h2></br>

<div class="container" id="new-container">
  <%= render 'students/student' %>
</div>